PROJECT_PHASE = "phase_4g_strategy_decision_composition_foundation"
STRATEGY_IMPLEMENTED = False
REAL_TRADING_ENABLED = False

FEATURE_SNAPSHOT_SCHEMA_VERSION = 1
CONTEXT_SNAPSHOT_SCHEMA_VERSION = 1
ANALYSIS_SNAPSHOT_SCHEMA_VERSION = 1

SYSTEM_STATE_SCAN_ENABLED = "scan_enabled"
SYSTEM_STATE_WORKER_HEARTBEAT = "worker_heartbeat"
SYSTEM_STATE_LAST_SUCCESSFUL_MARKET_FETCH = "last_successful_market_fetch"
SYSTEM_STATE_LAST_SUCCESSFUL_CALENDAR_FETCH = "last_successful_calendar_fetch"
SYSTEM_STATE_LAST_ERROR = "last_error"

DEFAULT_STRATEGY_VERSION = "foundation-v1"
