from enum import StrEnum


class Direction(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class Decision(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"
    REJECTED = "REJECTED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class AgentVerdict(StrEnum):
    CANDIDATE = "CANDIDATE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RiskStatus(StrEnum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    UNAVAILABLE = "UNAVAILABLE"


class SignalStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    APPROVED_NOT_DELIVERED = "APPROVED_NOT_DELIVERED"
    SENT = "SENT"
    WAITING_FOR_ENTRY = "WAITING_FOR_ENTRY"
    ENTERED = "ENTERED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    TP1_HIT = "TP1_HIT"
    TP2_HIT = "TP2_HIT"
    STOPPED = "STOPPED"
    CLOSED_MANUALLY = "CLOSED_MANUALLY"
    DATA_ERROR = "DATA_ERROR"


class MessageType(StrEnum):
    LONG_SIGNAL = "LONG_SIGNAL"
    SHORT_SIGNAL = "SHORT_SIGNAL"
    NO_TRADE = "NO_TRADE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    WARNING = "WARNING"
    REPORT = "REPORT"
    EDUCATION = "EDUCATION"
    CRITICAL_ERROR = "CRITICAL_ERROR"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    SYSTEM_STATUS = "SYSTEM_STATUS"
